build_failure_conditions:
    - 'elements.rating(<= D).exists'               # No classes/methods with a rating of D or worse
    - 'elements.rating(<= D).new.exists'           # No new classes/methods with a rating of D or worse allowed
    - 'issues.label("coding-style").exists'        # No coding style issues allowed
    - 'issues.label("coding-style").new.exists'    # No new coding style issues allowed
    - 'issues.severity(>= MAJOR).new.exists'       # New issues of major or higher severity
    - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 9
    - 'project.metric("scrutinizer.test_coverage", < 0.90)' # Code Coverage drops below 90%
    # Code Coverage decreased from previous inspection by more than 10%
    - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'
tools:
    php_code_sniffer:
        config:
            standard: "Symfony"
filter:
    excluded_paths:
        - 'src/*/Tests/'
    paths:
        - 'src/*'
checks:
    php: true
build:
    cache:
        directories:
            - vendor/
            - bin/
    environment:
        php:
            version: 5.4
    dependencies:
        override:
            - ./configure.sh
            - composer install --no-interaction
    tests:
        before:
            - ./app/console doctrine:database:create -e test
            - ./app/console doctrine:schema:create -e test
        override:
            -
                command: ./bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
