language: php
php:
  - 5.4
cache:
  directories:
    - vendor
    - bin
services:
  - mysql
install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - ./configure.sh
  - composer install --no-interaction
  - ./app/console doctrine:database:create -e test
  - ./app/console doctrine:schema:create -e test
script:
  - ./bin/phpunit
  - phpcs

