JahHub\FertilizerBundle\Entity\Week:
  exclusion_policy: ALL
  access_type: public_method
  properties:
    id:
      expose: true
      access_type: public_method
      type: integer
      read_only: true
    state:
      name: state
      expose: true
      access_type: public_method
      type: integer
      accessor:
        getter: getStateId
