imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    locale: en

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: fertilizer
    fragments:       ~
    http_method_override: true

twig:
    debug: "%kernel.debug%"
    strict_variables: true

assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [ ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Fertilizer Migrations

fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
            xml: true
            rss: false
        templating_formats:
            html: false
        force_redirects:
            html: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
              -
                path: '^/api$'
                priorities: ['json','xml']
                fallback_format: json
                prefer_extension: true
              -
                path: '^/api/doc$'
                stop: tue
    routing_loader:
        default_format: json
        include_format: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

nelmio_api_doc:
    name: Fertilizer API
