NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
jahhub_fertilizer_v1:
    type: rest
    prefix: /api/v1
    resource: "@JahHubFertilizerBundle/Resources/config/routing.yml"
