jahhub_fertilizer_item:
    type: rest
    prefix: /items
    resource: "JahHub\FertilizerBundle\Controller\ItemController"
    name_prefix:  api_1_item_ # naming collision
jahhub_fertilizer_state:
    type: rest
    prefix: /states
    resource: "JahHub\FertilizerBundle\Controller\StateController"
    name_prefix:  api_1_state_ # naming collision
jahhub_fertilizer_week:
    type: rest
    prefix: /weeks
    resource: "JahHub\FertilizerBundle\Controller\WeekController"
    name_prefix:  api_1_week_ # naming collision
jahhub_fertilizer_item_quantity:
    type: rest
    prefix: /item_quantities
    resource: "JahHub\FertilizerBundle\Controller\ItemQuantityController"
    name_prefix:  api_1_item_quantity_ # naming collision
