JahHub\FertilizerBundle\Entity\Item:
    properties:
        name:
            - NotBlank:
                message: "NOT_BLANK"
            - NotNull:
                message: "NOT_NULL"
            - Length:
                min: 3
                max: 100
                minMessage: "AT_LEAST_{min}"
                maxMessage: "NOT_MORE_THAN_{max}"
JahHub\FertilizerBundle\Entity\State:
    properties:
        name:
            - NotBlank:
                message: "NOT_BLANK"
            - NotNull:
                message: "NOT_NULL"
            - Length:
                min: 3
                max: 100
                minMessage: "AT_LEAST_{min}"
                maxMessage: "NOT_MORE_THAN_{max}"
JahHub\FertilizerBundle\Entity\ItemQuantity:
    properties:
        quantity:
            - NotNull:
                message: "NOT_NULL"
        item:
            - NotNull:
                message: "NOT_NULL"
        week:
            - NotNull:
                message: "NOT_NULL"
JahHub\FertilizerBundle\Entity\Week:
    properties:
        state:
            - NotNull:
                message: "NOT_NULL"
JahHub\FertilizerBundle\Entity\Schedule:
    properties:
        name:
            - NotBlank:
                message: "NOT_BLANK"
            - NotNull:
                message: "NOT_NULL"
            - Length:
                min: 3
                max: 100
                minMessage: "AT_LEAST_{min}"
                maxMessage: "NOT_MORE_THAN_{max}"
