JahHub\FertilizerBundle\Entity\Item:
    properties:
        name:
            - NotBlank:
                message: "NOT_BLANK"
            - NotNull:
                message: "NOT_NULL"
            - Length:
                min: 2
                max: 50
                minMessage: "AT_LEAST_{min}"
                maxMessage: "NOT_MORE_THAN_{max}"
